language: bash
sudo: required
services: docker

env:
  global:
    - VERSION: "3.11.0"
    - BUILD_DATE: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
    - TAG: $(echo ${VERSION}-alpine)
    - IMAGE: cassandra
    - REPO: $DOCKER_USERNAME
    - VCS_REF: "0.7"
    - TAG_MINOR: ${VERSION%.*}-alpine
    - TAG_MAJOR: ${VERSION%%.*}-alpine
    - BATS_VER: 0.4.0
    - GIT_REPO_LINK: "https://github.com/OlegGorj/cassandra-on-docker.git"

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake

before_install:
  - docker info
  - docker version
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

install:
  - sudo pip install docker-compose
  - curl -sSL https://s3.amazonaws.com/circle-downloads/install-circleci-docker.sh | bash -s -- 1.10.0
#  - git clone https://github.com/OlegGorj/cassandra-on-docker.git ~/cassandra-on-docker
  - make all
  - docker images
  - docker push $DOCKER_USERNAME/$IMAGE

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  rm -rf kcov-master &&
  mkdir -p coverage &&
  kcov coverage entrypoint.sh &&
  bash <(curl -s https://codecov.io/bash)
